Update and rename set_paths.py to set_paths.sh
does not work as python script, forever pends connection 8889

```
*********************************************
Your Google Colab instance is BlazingSQL ready!
*********************************************
--2019-11-13 02:19:45--  https://github.com/gumdropsteve/bsql-demos/raw/feature/utils/utils/set_paths.py
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/gumdropsteve/bsql-demos/feature/utils/utils/set_paths.py [following]
--2019-11-13 02:19:46--  https://raw.githubusercontent.com/gumdropsteve/bsql-demos/feature/utils/utils/set_paths.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 571 [text/plain]
Saving to: ‘set_paths.py’

set_paths.py        100%[===================>]     571  --.-KB/s    in 0s      

2019-11-13 02:19:46 (116 MB/s) - ‘set_paths.py’ saved [571/571]

Setting RAPIDS paths
SLF4J: The requested version 1.6 by your slf4j binding is not compatible with [1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
/usr/local/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/usr/local/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice/.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
Usage: blazingsql-engine <RAL_ID> <GPU_ID> <ORCHESTRATOR_HTTP_COMMUNICATION_[IP|HOSTNAME]> <ORCHESTRATOR_HTTP_COMMUNICATION_PORT> <RAL_HTTP_COMMUNICATION_[IP|HOSTNAME]> <RAL_HTTP_COMMUNICATION_PORT> <RAL_TCP_PROTOCOL_PORT> <OPTIONAL_NETWORK_INTERFACE_NAME_ETH0_DEFAULT>
RAL Engine starting
Using the network interface: eth0
RAL ID: 1
GPU ID: 0
Orchestrator HTTP communication host: 127.0.0.1
Orchestrator HTTP communication port: 9100
RAL HTTP communication host: 172.28.0.2
RAL HTTP communication port: 9001
RAL protocol port: 8891
Socket Name: 172.28.0.2
Log Name: RAL.1.log
RAL TCP protocol port: 8891
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:126)
	at com.blazingdb.calcite.application.TCPClient.send(TCPClient.java:38)
	at com.blazingdb.calcite.application.TCPClient.send(TCPClient.java:55)
	at com.blazingdb.calcite.application.TCPService.synchronizeSchema(TCPService.java:63)
	at com.blazingdb.calcite.application.TCPService.<init>(TCPService.java:53)
	at com.blazingdb.calcite.application.CalciteApplication.main(CalciteApplication.java:204)
schema synchronization with Orchestrator failed
Waiting for messages in TCP port: 8890
```